### ISSUE TITLE
possible issue with babel (using latest and async to gen)

### ISSUE THREAD

**Issue by robbiemu** [the-nobody/twitter-promise#2]
I have just aobut the simplest possible twitter server
```js
import TwitterPromise from 'twitter-promise'

class TwitterServer extends TwitterPromise {
  constructor(auth) {
    super(auth);
  }
  
  async get (id) {
    return await twitter.getTweet({id})
  }
}
 
module.exports = TwitterServer
```

when I run that in my koa server I get:

```
[nodemon] starting `node index.js`
C:\Users\roberto\github\CMST301-project2\src\twitter\index.js:25
    return _possibleConstructorReturn(this, (TwitterServer.__proto__ || Object.getPrototypeOf(TwitterServer)).call(this, auth));
                                                                                                              ^

TypeError: Class constructor Twitter cannot be invoked without 'new'
    at new TwitterServer (C:/Users/roberto/github/CMST301-project2/src/twitter/index.js:4:21)
    at Object.<anonymous> (C:/Users/roberto/github/CMST301-project2/server.js:12:17)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\roberto\github\CMST301-project2\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\roberto\github\CMST301-project2\node_modules\babel-register\lib\n
ode.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```

.babelrc
```json
{
  "presets": [ "latest"],
  "plugins" : ["transform-async-to-generator", "syntax-async-functions"]
}
```

babel compiled source:
```js
'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _twitterPromise = require('twitter-promise');

var _twitterPromise2 = _interopRequireDefault(_twitterPromise);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var TwitterServer = function (_TwitterPromise) {
  _inherits(TwitterServer, _TwitterPromise);

  function TwitterServer(auth) {
    _classCallCheck(this, TwitterServer);

    return _possibleConstructorReturn(this, (TwitterServer.__proto__ || Object.getPrototypeOf(TwitterServer)).call(this, auth));
  }

  _createClass(TwitterServer, [{
    key: 'get',
    value: function () {
      var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(id) {
        return regeneratorRuntime.wrap(function _callee$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                _context.next = 2;
                return twitter.getTweet({ id: id });

              case 2:
                return _context.abrupt('return', _context.sent);

              case 3:
              case 'end':
                return _context.stop();
            }
          }
        }, _callee, this);
      }));

      function get(_x) {
        return _ref.apply(this, arguments);
      }

      return get;
    }()
  }]);

  return TwitterServer;
}(_twitterPromise2.default);

module.exports = TwitterServer;
```

**Comment by robbiemu** [comment]
I apologize about the get call in the code above. Reading the readme.MD file, I expected this library to support the same calls and parameters as the actual twitter-node-client library. I'll have to go back to that probably.
